<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>IconGen</AssemblyName>
    <RootNamespace>IconGen</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpVectors" Version="1.8.5" />
  </ItemGroup>

</Project>
