<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>jiahao_payload</AssemblyName>
    <RootNamespace>Payload_Dumper_C_</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.25.3" />
    <PackageReference Include="Grpc.Tools" Version="2.66.0" PrivateAssets="All" />
    <PackageReference Include="SharpCompress" Version="0.37.0" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="App.xaml.cs" />
    <Compile Remove="AssemblyInfo.cs" />
    <Compile Remove="MainWindow.xaml.cs" />
    <Page Remove="App.xaml" />
    <Page Remove="MainWindow.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\update_metadata.proto" GrpcServices="None" />
  </ItemGroup>

</Project>
